### ISSUE TITLE
Doesn't parse Blobs correctly

### ISSUE THREAD

**Issue by madmandrew** [sneas/ionic-native-http-connection-backend#96] opened 2019-12-09 00:58 UTC
It appears this plugin doesn't parse blob data correctly.

I've made GET request for both an image and video file and neither work with this plugin

**Comment by sneas** [comment] 2019-12-09 09:31
Hi, thank you for rasing the  the issue. Could you please provide a reproducible example?
Feel free to fork https://github.com/sneas/ionic-4-http-test it already contains necessary presets for up and running.

**Comment by sneas** [comment] 2019-12-24 14:12
Closing the issue due to the inability to reproduce the problem.

**Closed by sneas** 2019-12-24 14:12 UTC
