### ISSUE TITLE
APP_INITIALIZER problem?

### ISSUE THREAD

**Issue by digaus** [sneas/ionic-native-http-connection-backend#62] opened 2018-12-13 16:20 UTC
Hello,
I tried to use this plugin in our project but it seems that due to our APP_INITIALIZER which loads JSON files via HttpClient before the app initializes that the request fail because the platform is not ready yet.

Any ideas about a solution?

**Comment by sneas** [comment] 2018-12-13 16:50
Hi,

If you're using angular > 4.3 and HttpClientModule this should not be the case because plugin waits for the app to be initialised before taking any actions. You can see it here

https://github.com/sneas/ionic-native-http-connection-backend/blob/master/src/native-http-fallback.ts#L20

Have you tried this https://github.com/sneas/ionic-native-http-connection-backend/blob/master/TROUBLESHOOTING.md ?

**Comment by digaus** [comment] 2018-12-14 06:49
Hmm ok will have to look into that further as the app will not start when useing the plugin (just blank white)

**Comment by sneas** [comment] 2018-12-15 17:35
Hi @digaus,

I tried to reproduce your problem in this test project https://github.com/sneas/ionic-4-http-test but the library works as expected. You can find APP_INITIALIZER implementation in [app-initializer](https://github.com/sneas/ionic-4-http-test/blob/app-initializer/src/app/app.module.ts#L25) branch.

May the fact the test project uses `ionic-native-http-connection-backend` v5.0.2 and Ionic 4. From the Angular's perspective it's similar to v4.0.8 and Ionic 3. Anyway I'll recheck it with v4.0.8 and Ionic 3 the next week and let you know if it has any problems.

Btw if you want to experiment with the test project I created you can run `npm run prod` command. It will compile project with `--prod` flag and open xcode for further deploy on device or emulator.

Also I have to mention the library falls back to XmlHttpRequest usage as soon as it can't recognize `cordova-plugin-advanced-http` or the request contains relative URL. All URLs must start with `http(s)://` for the library use `@ionic-native/http` as the connection backend for HttpClient. This is the limitation of Cordova's plugin. It doesn't like relative URLs. [Here is the fallback's implementation](https://github.com/sneas/ionic-native-http-connection-backend/blob/master/src/native-http-fallback.ts#L27).

Good luck with it and please let me know when you find the cause of the trouble.

**Comment by sneas** [comment] 2019-01-13 15:53
Closing due to inability to reproduce the issue

**Closed by sneas** 2019-01-13 15:53 UTC
