### ISSUE TITLE
Doesn't work with ionic serve and always get cors error

### ISSUE THREAD

**Issue by db-conception** [sneas/ionic-native-http-connection-backend#95] opened 2019-11-30 09:55 UTC
Hi, I get this message when I try to use your plugin in browser mode (ionic serve command) : 
`common.js:297 Native: tried accessing the undefined plugin but Cordova is not available. Make sure to include cordova.js or run in a device/simulator`
...then I get the CORS message. 

The code for the request is 

```ts
return this.http.handle(
    new HttpRequest("POST", this.baseurl+"ApiAccount/Register" ,{
        email:email,
        password:password
    }, {
        headers : new HttpHeaders().append("Content-Type", 'application/json')
    })
).toPromise().then(success => {
    let httpRep = success as HttpResponse<User>;
    if(httpRep.ok)
    {
        console.log("register success");
        console.log(httpRep.body);
        return this.storage.set(USER_KEY, httpRep.body).then(() => {
            this.authenticationState.next(true);
        });
    }
    else{
        console.log("not success");

    }

}).catch(err => {
    console.log(err);
});
```

I readed your troublshooting.md and tried the code, but I get 

> common.js:290 Native: tried calling HTTP.sendRequest, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
Instead of 

> cordova-plugin-advanced-http is installed properly

So, I tried to uninstall all plugins with next command : 

```bash
npm uninstall ionic-native-http-connection-backend
npm uninstall @ionic-native/http
ionic cordova plugin rm cordova-plugin-advanced-http
```

Then reinstall with

```bash
npm install --save ionic-native-http-connection-backend
ionic cordova plugin add cordova-plugin-advanced-http
npm install @ionic-native/http
```

But I always get the same trouble

Thank's for your help

**Comment by sneas** [comment] 2019-12-01 08:31
Your code looks correct.
You can refer to this repo for a working example https://github.com/sneas/ionic-4-http-test
I've created `request` branch for you https://github.com/sneas/ionic-4-http-test/tree/request
It's been tested in a browser and in iOS simulator. Works properly on both.

The request example https://github.com/sneas/ionic-4-http-test/blob/request/src/app/tab1/tab1.page.ts#L11

Module initialization https://github.com/sneas/ionic-4-http-test/blob/request/src/app/app.module.ts#L22

**Comment by sneas** [comment] 2019-12-09 08:29
Closing due to an inability to reproduce the problem.

**Closed by sneas** 2019-12-09 08:29 UTC

**Comment by db-conception** [comment] 2019-12-22 22:40
Hi,

Sorry for answering you late.

I pull your branch and in youe exemple, you only try get. So, I added a post request next to and I can see on the network tab of chrome sur OPTIONS request sended. 

`this.httpClient.post('https://httpbin.org/post',
      {
        a:"b"
      }, {
      headers: new HttpHeaders({
        'content-type': 'application/json'
      })
    }).subscribe((data) => {
      console.log('Data', data);
    });`

PS : I already get the same warning.

**Comment by sneas** [comment] 2019-12-24 14:11
@db-conception, you don't have Cordova environment and in Chrome, that's why the library falls back to regular XmlHttpRequest. To see it's working in Cordova environment and uses `native-http-connection-backend` instead of XmlHttpRequest you got to run your app on an actual device (not the browser or device's browser).
